// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-cat': string;
  'add-linked-list-event': string;
  'blend': string;
}
export const cssExports: CssExports;
export default cssExports;
