// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-cat': string;
  'addCat': string;
  'pet': string;
}
export const cssExports: CssExports;
export default cssExports;
