// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cat-list-item': string;
  'catListItem': string;
}
export const cssExports: CssExports;
export default cssExports;
