// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cat-queue': string;
  'catQueue': string;
  'processed-cats': string;
  'processedCats': string;
}
export const cssExports: CssExports;
export default cssExports;
